cookie:
  expiry_days: 30
  key: some_key
  name: trkn-cook
credentials:
  usernames:
    dbaldwin:
      email: jeremydiliotti@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: trhacknon
      password: $2b$12$E9/bCaN/r8sN/FV2l8NpgOgspUBAp7UAVU6BgsXJzp/pW8gQWCprC
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - mdelaclaire@gmail.com
